export const API_URL = 'http://localhost:5000';

export const FETCH_LIST_REQUEST = 'FETCH_LIST_REQUEST';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAILED = 'FETCH_LIST_FAILED';

export const FETCH_LIST_ITEM_REQUEST = 'FETCH_LIST_ITEM_REQUEST';
export const FETCH_LIST_ITEM_SUCCESS = 'FETCH_LIST_ITEM_SUCCESS';
export const FETCH_LIST_ITEM_FAILED = 'FETCH_LIST_ITEM_FAILED';

export const FETCH_PHOTO_REQUEST = 'FETCH_PHOTO_REQUEST';
export const FETCH_PHOTO_SUCCESS = 'FETCH_PHOTO_SUCCESS';
export const FETCH_PHOTO_FAILED = 'FETCH_PHOTO_FAILED';

export const FETCH_PHOTO_ITEM_REQUEST = 'FETCH_PHOTO_ITEM_REQUEST';
export const FETCH_PHOTO_ITEM_SUCCESS = 'FETCH_PHOTO_ITEM_SUCCESS';
export const FETCH_PHOTO_ITEM_FAILED = 'FETCH_PHOTO_ITEM_FAILED';

export const FETCH_RESULT_REQUEST = 'FETCH_RESULT_REQUEST';
export const FETCH_RESULT_SUCCESS = 'FETCH_RESULT_SUCCESS';
export const FETCH_RESULT_FAILED = 'FETCH_RESULTS_FAILED';

export const FETCH_RESULT_ITEM_REQUEST = 'FETCH_RESULT_ITEM_REQUEST';
export const FETCH_RESULT_ITEM_SUCCESS = 'FETCH_RESULT_ITEM_SUCCESS';
export const FETCH_RESULT_ITEM_FAILED = 'FETCH_RESULT_ITEM_FAILED';

export const FETCH_GAME_REQUEST = 'FETCH_GAME_REQUEST';
export const FETCH_GAME_SUCCESS = 'FETCH_GAME_SUCCESS';
export const FETCH_GAME_FAILED = 'FETCH_GAME_FAILED';
